# Generated by Django 3.1 on 2020-08-10 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0004_auto_20200810_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='device',
        ),
        migrations.AddField(
            model_name='devicedata',
            name='device_id',
            field=models.ForeignKey(default=9999999, on_delete=django.db.models.deletion.CASCADE, to='ambiente.device', to_field='device_id'),
            preserve_default=False,
        ),
    ]
