# Generated by Django 3.0.8 on 2020-08-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0005_auto_20200810_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='moisture',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
